# Pandas

In [1]:
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
import pandas as pd
import os

In [3]:
os.chdir("/home/lyonsja/Python/Data/")
print('Current working directory:\n'+os.getcwd())

Current working directory:
/home/lyonsja/Python/Data

In [4]:
s = pd.Series([1, 2, 3, 4, 5])
s.rolling(3).sum()

0     NaN
1     NaN
2     6.0
3     9.0
4    12.0
dtype: float64

In [18]:
# Import a data frame from a compressed CSV stored online.
url1="https://github.com/gedeck/practical-statistics-for-data-scientists/blob/master/data/sp500_data.csv.gz?raw=True"
sp500_px=pd.read_csv(url1, compression="gzip")

In [5]:
# Import a data frame from a CSV file
trolley=pd.read_csv("TrolleyGAR.csv")
trolley.head()

   Hospital.Code Target.Date  Total.2pm  Total.8pm  Total.8am
0            101  01/01/2013        1.0        0.0          2
1            102  01/01/2013       12.0        8.0         11
2            108  01/01/2013        4.0       10.0          9
3            201  01/01/2013        3.0        4.0          9
4            202  01/01/2013        0.0        0.0          5

In [13]:
# Rename columns
trolley=trolley.rename(columns={"Target.Date":"date", "Hospital.Code":"provider", 
                                "Total.8am":"value8am","Total.2pm":'value2pm',
                               'Total.8pm':'value8pm'})

In [14]:
# How many rows have null values?
print(trolley.isnull().sum())

provider     0
date         0
value2pm    61
value8pm    89
value8am     0
dtype: int64

In [15]:
# Melt data frame (if there's a column called value or variable it needs to be renamed).
trolley.melt(id_vars=["provider","date"]).sample(4)

        provider        date  variable  value
330238       904  09/02/2023  value8am   32.0
228553       501  30/06/2013  value8am    0.0
322015       800  01/05/2022  value8am   22.0
328976       500  27/12/2022  value8am   16.0

In [16]:
# Remove selected columns.
trolley=trolley.drop(columns=['value2pm','value8pm'])

In [17]:
# Replace values
trolley.provider=trolley.provider.replace([101,108,500],[1,2,3])

In [18]:
# Remapping column values.
t2=trolley.query('provider in (102,201,800)')
t2['provider']=t2.provider.map({102:'Provider A', 201:'Provider B', 800:'Provider C'})
t2.sample(5)

         provider        date  value8am
22634  Provider A  27/02/2015        17
15529  Provider A  27/06/2014         5
59904  Provider B  04/09/2018         2
94555  Provider A  16/12/2021        10
27332  Provider A  08/08/2015        17

In [19]:
# A list of the column names
list(trolley.columns)

['provider', 'date', 'value8am']

In [20]:
# Print the shape of the data frame. 
print("TrolleyGAR Data\n{} rows and {} columns".format(trolley.shape[0], 
                                                       trolley.shape[1]))

TrolleyGAR Data
111751 rows and 3 columns

In [21]:
# Find rows with NaN values in date column.
trolley[trolley.date.isna()]

Empty DataFrame
Columns: [provider, date, value8am]
Index: []

In [22]:
# Find any rows with NaN values.
trolley[trolley.isna().any(axis=1)]

Empty DataFrame
Columns: [provider, date, value8am]
Index: []

In [23]:
# Remove rows with NaN values in date column.
trolley=trolley.dropna(axis=0, subset=["date"])
trolley.shape

(111751, 3)

In [24]:
# Replace NaNs in value column with 0.
trolley.value8am=trolley.value8am.fillna(0)

In [25]:
# Change a column data type
trolley["value8am"]=trolley["value8am"].astype(float)
trolley.provider=trolley.provider.astype(int)

In [26]:
# Add an additional row.
trolley=pd.concat([trolley, pd.DataFrame({"provider":[923], 
                                  "date":["11/11/2024"], 
                                  "value8am": [5]
                                 })], axis=0)

In [27]:
# Find duplicated rows
trolley[trolley.duplicated()]

Empty DataFrame
Columns: [provider, date, value8am]
Index: []

In [28]:
# Remove duplicated rows
trolley=trolley.drop_duplicates()
trolley.shape

(111752, 3)

In [29]:
# Create a table of the character lengths of a str type column.
pd.DataFrame(trolley.date.astype(str).str.len().value_counts()).rename_axis('str_len')

          count
str_len
10       111752

In [30]:
# Convert the date column to a datetime object, this will convert the format to yyyy-mm-dd.
trolley.date=pd.to_datetime(trolley.date, format="%d/%m/%Y")
trolley.sample(5)

        provider       date  value8am
85874          3 2021-02-17       4.0
60939        800 2018-10-09      32.0
24158        800 2015-04-20      28.0
47658        941 2017-07-08       2.0
104955       501 2022-12-09      30.0

In [31]:
# A sequence of dates from X to Y.
pd.date_range(start="1992-01-28", end="1992-02-07", freq='D')

DatetimeIndex(['1992-01-28', '1992-01-29', '1992-01-30', '1992-01-31',
               '1992-02-01', '1992-02-02', '1992-02-03', '1992-02-04',
               '1992-02-05', '1992-02-06', '1992-02-07'],
              dtype='datetime64[ns]', freq='D')

In [32]:
# A sequence of the last 14 days.
pd.date_range(end='2024-11-14', periods=14)

DatetimeIndex(['2024-11-01', '2024-11-02', '2024-11-03', '2024-11-04',
               '2024-11-05', '2024-11-06', '2024-11-07', '2024-11-08',
               '2024-11-09', '2024-11-10', '2024-11-11', '2024-11-12',
               '2024-11-13', '2024-11-14'],
              dtype='datetime64[ns]', freq='D')

In [33]:
# Create a new column for year, month and day.
trolley["year"]=trolley.date.dt.year
trolley["month"]=trolley.date.dt.month
trolley['day']=trolley.date.dt.day
trolley.sample(3)

        provider       date  value8am  year  month  day
108544       402 2023-04-12       2.0  2023      4   12
65475          2 2019-03-15       3.0  2019      3   15
64351        913 2019-02-04      13.0  2019      2    4

In [34]:
# Use the apply method and lambda function to create a if-else column
trolley['season'] = trolley.month.apply(lambda x: 'winter' if x in [1,2,12] else
                                        'spring' if x in [3,4,5] else 
                                        'summer' if x in [6,7,8] else 'autumn')

trolley.sample(3)

       provider       date  value8am  year  month  day  season
3505        203 2013-05-06       8.0  2013      5    6  spring
42617         2 2017-01-16       4.0  2017      1   16  winter
28956       209 2015-10-03      14.0  2015     10    3  autumn

In [35]:
# Data frame overview
trolley.info()

<class 'pandas.core.frame.DataFrame'>
Index: 111752 entries, 0 to 0
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   provider  111752 non-null  int64
 1   date      111752 non-null  datetime64[ns]
 2   value8am  111752 non-null  float64
 3   year      111752 non-null  int32
 4   month     111752 non-null  int32
 5   day       111752 non-null  int32
 6   season    111752 non-null  object
dtypes: datetime64[ns](1), float64(1), int32(3), int64(1), object(1)
memory usage: 5.5+ MB

In [36]:
# Sort by provider then date and reset the index
trolley=trolley.sort_values(['provider','date']).reset_index(drop=True)
trolley.tail(3)

        provider       date  value8am  year  month  day  season
111749      1049 2023-07-29       8.0  2023      7   29  summer
111750      1049 2023-07-30      10.0  2023      7   30  summer
111751      1049 2023-07-31      14.0  2023      7   31  summer

In [37]:
# Show the first four rows of columns date and value8am.
trolley[0:4][["date","value8am"]]

        date  value8am
0 2013-01-01       2.0
1 2013-01-02      10.0
2 2013-01-03       6.0
3 2013-01-04       9.0

In [38]:
# Print rows 0 to 5 for columns date and value.
trolley.loc[0:5, ['date','value8am']]

        date  value8am
0 2013-01-01       2.0
1 2013-01-02      10.0
2 2013-01-03       6.0
3 2013-01-04       9.0
4 2013-01-05       1.0
5 2013-01-06       4.0

In [39]:
# Show the first five rows and first three columns.
trolley.iloc[0:5, 0:3]

   provider       date  value8am
0         1 2013-01-01       2.0
1         1 2013-01-02      10.0
2         1 2013-01-03       6.0
3         1 2013-01-04       9.0
4         1 2013-01-05       1.0

In [44]:
# Group by two columns and aggregate sum over a third numeric column.
agg_df=trolley[['provider','year','month','value8am']].groupby(
    by=['provider','year','month'], as_index=False).agg({'value8am':['sum']})
agg_df.columns=['provider','year','month','total_value8am']
agg_df.head()

   provider  year  month  total_value8am
0         1  2013      1           207.0
1         1  2013      2           185.0
2         1  2013      3           164.0
3         1  2013      4           147.0
4         1  2013      5           168.0

In [45]:
# Calculate a running total for each provider and year.
agg_df['running_total']=agg_df.groupby(by=['provider','year']).total_value8am.cumsum()
agg_df.head()

   provider  year  month  total_value8am  running_total
0         1  2013      1           207.0          207.0
1         1  2013      2           185.0          392.0
2         1  2013      3           164.0          556.0
3         1  2013      4           147.0          703.0
4         1  2013      5           168.0          871.0

In [48]:
# Pivot table
pivotDF=agg_df.query('provider == 923').pivot(index='month', 
                                              columns='year', values='total_value8am').fillna(0)

for i in pivotDF.columns:
    pivotDF[i] = pivotDF[i].astype(int)

pivotDF

year   2013  2014  2015  2016  2017  2018  2019  2020  2021  2022  2023  2024
month
1       817   737   756   871   465   353   269   252     0     0   267     0
2       786   657   869   704   520   308   309   224     0    54   160     0
3       742   450   764   851   336   192   257    39     0   113    70     0
4       860   610   720   823   195   127   345     0     0   163    33     0
5       545   349   853   589   290   247   211     0     0   133    46     0
6       492   311   759   584   304   102   173     0     0    55    43     0
7       641   609   632   418   376    61    79     0     0    37    13     0
8       585   589   734   405   264   142    74     0     0    29     0     0
9       647   695   792   413   251   226   166     0     0    41     0     0
10      707   715   882   408   334   254    97     0     0    77     0     0
11      751   860   660   382   261   188   275     0     0   155     0     5
12      630   684   586   486   282   226   170     0     0   106     0     0

In [49]:
# Create a table of the number of rows for each distinct value in a selected column.
pd.DataFrame(trolley.year.value_counts()).sort_index(ascending=False).head(4)

      count
year
2024      1
2023   6148
2022  10585
2021  10527

In [50]:
# A list of the unique values of a selected column.
uniuqeYears=list(trolley.year.unique())
uniuqeYears[0:10]

[np.int32(2013),
 np.int32(2014),
 np.int32(2015),
 np.int32(2016),
 np.int32(2017),
 np.int32(2018),
 np.int32(2019),
 np.int32(2020),
 np.int32(2021),
 np.int32(2022)]

In [51]:
# Subset condition and random sample.
trolley[(trolley.year > 2013) & (trolley.year < 2024)][["date","year"]].sample(5)

             date  year
12542  2014-09-24  2014
108493 2014-08-25  2014
1917   2017-05-06  2017
111356 2022-07-01  2022
46070  2021-05-29  2021

In [52]:
# Alternatively one can use the query() method.
trolley.query("year > 2013 and year < 2024").sample(6)

       provider       date  value8am  year  month  day  season
15416       201 2022-08-11       2.0  2022      8   11  summer
84923       908 2022-02-07      26.0  2022      2    7  winter
2711          2 2019-07-09       8.0  2019      7    9  summer
4648          3 2014-04-03      18.0  2014      4    3  spring
80288       904 2019-12-21       4.0  2019     12   21  winter
47326       601 2014-04-09       8.0  2014      4    9  spring

In [53]:
# A statistical summary of the data frame.
trolley.describe()

,provider,date,value8am,year,month,day
count,111752.000000,111752,111752.000000,111752.000000,111752.000000,111752.000000
mean,591.250465,2018-04-18 17:01:22.210609408,8.703048,2017.807395,6.393953,15.731020
min,1.000000,2013-01-01 00:00:00,0.000000,2013.000000,1.000000,1.000000
25%,300.000000,2015-08-28 00:00:00,1.000000,2015.000000,3.000000,8.000000
50%,607.000000,2018-04-18 00:00:00,6.000000,2018.000000,6.000000,16.000000
75%,908.000000,2020-12-08 00:00:00,14.000000,2020.000000,9.000000,23.000000
max,1049.000000,2024-11-11 00:00:00,70.000000,2024.000000,12.000000,31.000000
std,322.203184,NaN,9.215515,3.056601,3.435409,8.796029

In [54]:
# Group by two columns and aggregate calculation.
trolley.query("year == 2019").groupby(by=["provider","month"], as_index=False).agg(
    {"value8am":["mean",'sum']})[0:5]

  provider month  value8am
                      mean    sum
0        2     1  6.516129  202.0
1        2     2  6.321429  177.0
2        2     3  6.354839  197.0
3        2     4  4.866667  146.0
4        2     5  4.516129  140.0

In [55]:
# Calculate the 30 day moving average.
trolley['30DMA']=0
for i in range(len(trolley)):
    provider_i=trolley.loc[i, ['provider']][0]
    date_i=trolley.loc[i, ['date']][0]
    last30Days=pd.date_range(end=date_i, periods=30)
    moving_average_i=trolley[
    (trolley.date.isin(last30Days)) & 
    (trolley.provider==provider_i)].value8am.mean()
    trolley.loc[i, '30DMA']=moving_average_i

trolley.tail()

        provider       date  value8am  year  month  day  season      30DMA
111747      1049 2023-07-27      13.0  2023      7   27  summer  25.700000
111748      1049 2023-07-28      11.0  2023      7   28  summer  24.566667
111749      1049 2023-07-29       8.0  2023      7   29  summer  23.533333
111750      1049 2023-07-30      10.0  2023      7   30  summer  22.600000
111751      1049 2023-07-31      14.0  2023      7   31  summer  21.966667

In [56]:
# Write data frame to CSV.
trolley.sample(10).to_csv("trolleySample.csv", index=False)

-------------------------------

In [5]:
# Import CSV data from a directory
path1='C:/Users/C10381149/OneDrive - Technological University Dublin/Documents/Python/'
path2='Datasets/PET_Data'
os.chdir(path1+path2)
pet=pd.DataFrame({'provider':[],'mrn':[],'reg':[],'age':[],
                  'triage':[],'edclinician':[],'depart':[],'destination':[]})
for f in os.listdir():
    pet=pd.concat([pet, pd.read_csv(f, header=0, names=pet.columns)])

pet.sample(3)

,provider,mrn,reg,age,triage,edclinician,depart,destination
83743,501.0,80B7E9701E0E0A8A1915F7B513F56663,26/12/2017 04:15,84.0,26/12/2017 04:16,26/12/2017 06:57,26/12/2017 10:43,Admitted to Ward
6555,908.0,7375EE4C0BB4F23C06573D9D6E47B3D6,01-Feb-2022 12:24:00,27.0,01-Feb-2022 12:52:00,01-Feb-2022 15:02:00,01-Feb-2022 20:33:00,Discharged Home
72448,809.0,2FFC87B7D4D89913D9BE1261D2776AFD,19-Apr-2023 22:09:00,36.0,19-Apr-2023 22:14:00,NaN,20-Apr-2023 09:30:00,Admitted to Ward

In [6]:
pet=pet[(pet.reg.astype(str).str.len()==20) & (pet.age.isin(range(0,121)))]
pet.head(3)

,provider,mrn,reg,age,triage,edclinician,depart,destination
0,724.0,FB2AB1B262390E572A6235ACA77CF5AE,18-Dec-2021 08:26:00,50.0,18-Dec-2021 08:33:00,NaN,18-Dec-2021 09:30:00,Referred to OPD
1,724.0,7623E9DCE9D56124AC5F9ED13EF7DC31,18-Dec-2021 08:59:00,12.0,18-Dec-2021 09:03:00,NaN,18-Dec-2021 09:44:00,Discharged Home
2,724.0,2AF045BEC86AEDEBBF7B82AC2294F4DD,18-Dec-2021 09:03:00,2.0,18-Dec-2021 09:08:00,18-Dec-2021 10:35:00,18-Dec-2021 10:45:00,Discharged Home

In [7]:
# Change timestamp columns from character strings to datetime objects
for i in ['reg','triage','edclinician','depart']:
    pet[i] = pd.to_datetime(pet[i], format="%d-%b-%Y %H:%M:%S")

In [8]:
# Patient experience time
pet['pet'] = (pet.depart - pet.reg)/pd.Timedelta(hours=1)

In [12]:
# Change the date format
pet['week_day']=pet.reg.dt.strftime('%A')
pet[['reg','week_day']].head()

                  reg  week_day
0 2021-12-18 08:26:00  Saturday
1 2021-12-18 08:59:00  Saturday
2 2021-12-18 09:03:00  Saturday
3 2021-12-18 09:13:00  Saturday
4 2021-12-18 09:18:00  Saturday

In [152]:
# Merge two data frames on a date column.
meanPET=pet.groupby(by=['provider','depart'], as_index=False).aggregate({'pet':'mean'})
meanPET.columns=['provider','date','meanPET']
mergedDF=pd.merge(left=meanPET, right=trolley[['provider','date','value8am']],
                  left_on=['provider','date'], right_on=['provider','date'],
                  how='inner').sort_values(['provider','date'])
mergedDF.head()

   provider       date    meanPET  value8am
0     102.0 2016-11-30   2.866667      21.0
1     102.0 2016-12-07   0.583333       7.0
2     102.0 2016-12-28   4.866667      10.0
3     102.0 2016-12-31   2.383333       2.0
4     102.0 2017-01-04  13.533333      17.0

In [56]:
# Import an excel spreadsheet
dd=pd.read_excel('DD National Report 2018-07-31.xls', 
              sheet_name='Delayed Discharges', header=1)
dd.columns=['provider','','last_week','this_week','difference','',
            'on','off','','home','nhss',
            'other','rip','acute','','type_a','type_b','type_c']
dd=dd[dd.columns[dd.columns != '']]
dd=dd[dd.provider.isna()==False]
dd=dd[dd.provider != ' '].reset_index(drop=True)
dd.head()

,provider,last_week,this_week,difference,on,off,home,nhss,other,rip,acute,type_a,type_b,type_c
0,992,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,941,3.0,3.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
2,940,6.0,7.0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,2.0
3,201,7.0,7.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0
4,203,10.0,13.0,3.0,3,1.0,0.0,1.0,0.0,0.0,0.0,1.0,8.0,4.0

In [53]:
# Get the name of the last column
dd.iloc[:,-1].name

'type_c'